name: novelizenow-back

services:
  novelizenow-back:
    build: .
    image: novelizenow-back
    container_name: novelizenow-back
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - default
      - mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - novelizenow-back

networks:
  mysql:
    external: true
